// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bilimusic/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteCollectionAdapter());
    registerAdapter(FavoriteEntryAdapter());
    registerAdapter(FavoriteMembershipAdapter());
    registerAdapter(MetaLyricsAdapter());
    registerAdapter(MetadataAdapter());
    registerAdapter(PersistedPlayableItemAdapter());
    registerAdapter(PersistedPlaybackQueueAdapter());
    registerAdapter(PlayerQueueModeAdapter());
    registerAdapter(RecentPlaybackEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteCollectionAdapter());
    registerAdapter(FavoriteEntryAdapter());
    registerAdapter(FavoriteMembershipAdapter());
    registerAdapter(MetaLyricsAdapter());
    registerAdapter(MetadataAdapter());
    registerAdapter(PersistedPlayableItemAdapter());
    registerAdapter(PersistedPlaybackQueueAdapter());
    registerAdapter(PlayerQueueModeAdapter());
    registerAdapter(RecentPlaybackEntryAdapter());
  }
}
